[tool.poetry]
name = "nmass"
version = "0.1.0"
description = "A python3 library that makes it easier to use nmap and masscan"
authors = ["4shen0ne <4shen.01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic-xml = "^2.11.0"
aiofiles = "^24.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
